myset={1,2,3,4,5,6}
print(myset)
print(type(myset))
fruits=['apple','grapes','sapota']
print(fruits)
frozenset
a=frozenset([1,2,3,6,4])
print(a)
a=frozenset([1,2,3,4,5])
b=frozenset([7,8,9])
print(a.union(b))
print(a.intersection(b))